version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule: 
      interval: "daily"
      time: "16:02"
      timezone: "America/New_York"
    labels:
      - "docker-dependencies"