# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildx:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context : . 
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            markgreenway/dnsimple-dnyndns-arm:latest
            markgreenway/dnsimple-dnyndns-arm:run_${{  github.run_number }}
            ghcr.io/markgreenway/dnsimple-dnyndns-arm:latest
            ghcr.io/markgreenway/dnsimple-dnyndns-arm:run_${{ github.run_number }}
          push : true
#      - name: Publish to Github Packages 
#        uses : docker/build-push-action@v1
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GIHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          repository : ${{ github.repository}}/dnsimple-dyndns-arm
#          tags: latest, ${{  github.run_number }}